- hosts: localhost
  connection: local
  become: yes
  become_flags: '-i'

  tasks:
  - name: Update cache and update OS
    apt:
      upgrade: full
      update_cache: yes
    
  - name: Update cache and install packages
    apt:
      pkg:
      - ufw  
      - libemail-outlook-message-perl
      - mpack
    
  - name: Block incoming and enable UFW
    ufw:
      state: enabled
      direction: incoming
      policy: deny
  
  - name: Check if rockyou.txt.gz exists (Kali)
    stat:
      path: /usr/share/wordlists/rockyou.txt.gz
    register: rockyou_file
    
  - name: Run uncompress if rockyou exists
    command: gzip -d /usr/share/wordlists/rockyou.txt.gz
    when: rockyou_file.stat.exists
  
  - name: Check if default_keys exists
    stat:
      path: /etc/ssh/default_keys
    register: my_folder
    
  - name: echo if default_keys already exists
    debug:
      msg: "default_keys already exists"
    when: my_folder.stat.exists
    
  - name: Create /etc/ssh/default_keys if not exists
    file:
      path: /etc/ssh/default_keys
      state: directory
      mode: 0700
      group: root
      owner: root
    when: my_folder.stat.exists == false
    
  - name: Check if keys folder is empty before proceeding
    find:
      paths: '/etc/ssh/default_keys'
    register: filesFound
    
  - fail:
      msg: '/etc/ssh/default_keys folder is not empty.'
    when: filesFound.matched > 0

  - debug:
      msg: 'The /etc/ssh/default_keys folder is empty. Proceeding.'

  - name: Copy each ssh key over to /etc/ssh/default_keys
    copy:
       src: "{{ item }}"
       dest: "/etc/ssh/default_keys"
       owner: root
       group: root
       mode: 0755
    with_fileglob:
        - "/etc/ssh/ssh_host_*"
    
  - name: Delete existing ssh host keys
    file:
      path: "{{ item }}"
      state: absent
    with_fileglob:
        - "/etc/ssh/ssh_host_*"
    
  - name: Recreate keys
    command: dpkg-reconfigure openssh-server
