- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Update cache and update OS
    apt:
      upgrade: full
      update_cache: yes

  - name: Update cache and install packages
    apt:
      pkg:
      - ufw  
      - libemail-outlook-message-perl
      - mpack

  - name: Block incoming and enable UFW
    ufw:
      state: enabled
      direction: incoming
      policy: deny
  
  - name: Check if default_keys exists
    stat:
      path: /etc/ssh/default_keys
    register: my_folder
    
  - name: echo if directory already exists
    debug:
      msg: "default_keys already exists"
    when: my_folder.stat.exists
    
  - name: Ansible Create directory if not exists
    file:
      path: /etc/ssh/default_keys
      state: directory
      mode: 0755
      group: root
      owner: root
    when: my_folder.stat.exists == false
    
  - name: Check if keys folder is empty before proceeding
      find:
        paths: '/etc/ssh/default_keys'
      register: filesFound

  - fail:
      msg: '/etc/ssh/default_keys folder is not empty.'
    when: filesFound.matched > 0

  - debug:
      msg: 'The /etc/ssh/default_keys folder is empty. Proceeding.'
